**Question:**

***Randomly generate a matrix of shape (1Million, 2) and perform below mentioned operations:***

***a. Find the distances between each 2-Dimensional data point from the centroid (i.e. mean) of the given dataset. Append the newly calculated distances as new column with the given dataset.***

***b. Given any data point, generate 3 closest neighbors from it.***

In [1]:
import numpy as np

In [2]:
# step 1 : make a matrix of size (1000000, 2) randomly
matrix = np.random.rand(1000000,2)

In [3]:
matrix, matrix.shape

(array([[0.27877565, 0.10976973],
        [0.9511969 , 0.46520706],
        [0.92947834, 0.34761558],
        ...,
        [0.76408277, 0.32966261],
        [0.78963753, 0.55806856],
        [0.07886665, 0.81964271]]),
 (1000000, 2))

In [4]:
# step 2 : find the centroid of the data (mean)

# mean_x = np.mean(matrix[0])
# mean_y = np.mean(matrix[1])

# mean_x, mean_y
centroid = np.mean(matrix, axis = 0)
centroid

array([0.50018289, 0.49990311])

In [5]:
%%time
# step 3 : compute the distance between 2d datapoints and centroid(Numpy broadcasting)
distance = np.sqrt(np.sum((matrix-centroid)**2, axis = 1)) # axis = 1 is across row 

Wall time: 101 ms


In [6]:
distance.shape

(1000000,)

In [7]:
# step 4: add the distnace as a new column to our matrix
np.hstack([matrix, distance.reshape(-1,1)])

array([[0.27877565, 0.10976973, 0.44858135],
       [0.9511969 , 0.46520706, 0.4523466 ],
       [0.92947834, 0.34761558, 0.45550639],
       ...,
       [0.76408277, 0.32966261, 0.31404614],
       [0.78963753, 0.55806856, 0.29524093],
       [0.07886665, 0.81964271, 0.52890527]])

***b. Given any data point, generate 3 closest neighbors from it.***

In [8]:
test = np.random.rand(1,2)
# Calculate distance between test data and all points in matrix
distances = np.sqrt(np.sum((test - matrix)**2, axis = 1))
n = 3
min_indices = np.argpartition(distances,n-1)[:n]

In [9]:
min_indices

array([ 58450, 209434, 904965], dtype=int64)

In [10]:
# minimum distances 
distances[min_indices]

array([0.00088926, 0.00112255, 0.00131193])

In [11]:
# points at minimum distance:
matrix[min_indices]

array([[0.12340026, 0.98196863],
       [0.12149225, 0.98258468],
       [0.12223147, 0.98343946]])